config/routes.rb
SampleApp2::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :microposts, :only => [:create, :destroy]
  
  resources :relationships, :only => [:create, :destroy]

  
  
  match '/signup', :to => 'users#new'
  
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact' # route link to the pages_controller
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  root :to => 'pages#home'
  

  

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", "http://www.google.com/url?sa=t&source=web&cd=1&sqi=2&ved=0CBsQ9gkwAA&url=https%3A%2F%2Fplus.google.com%2F104351659388731279799&ei=oFqbTs35IeX40gG2haSTAQ&usg=AFQjCNEjpJnWYqeUHjDJl9fHPX_JptdmOg", :target => '_blank'%> </li>
	  <li><%= link_to "Rails Tutorial", "http://www.railstutorial.org/", :target => '_blank'%>
      <!-- <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- Creating a PARTIAL header as a helper -->

<header>
	<!-- was this definition for the logo -->
	<!-- <percent= image_tag("logo.png", :alt => "Sample App", :class => "round") percent> -->
	<!--  Changed it to this -->
	<!-- Notice it's not <percent= because we don't want it inserted into the template -->
	<!-- defines the logo, which logo it is found in 'images' -->	
	<!-- <percent logo = image_tag("logo.png", :alt => "Sample App", :class => "round") percent> -->
	
	<!--    NOW MOVED THE ABOVE DEFINITION TO THE APPLICATION HELPER    -->
	
	<!-- link the logo to root_path -->
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
		  <li><%= link_to "Home", root_path %></li>
		  <% if signed_in? %>
		  <li><%= link_to "Users", users_path %></li>
		  <li><%= link_to "Profile", current_user %></li>
		  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
		  <% end %>
		  <li><%= link_to "Help", help_path %></li>
		  <% if signed_in? %>
		  <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		  <% else %>
		  <li><%= link_to "Sign in", signin_path %></li>
		  <% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!-- Creating a PARTIAL as a helper -->

<!-- some stuff for IE - internet explorer compatibility -->
<!--[if lt IE 9]>
<script src ="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Rails helper stylesheet_link_tag (read about in API)
includes the blueprint/screen.css for screens, and the other for printing
Rails looks in the public/stylesheets folder by default, so only need 
the continuation to 'blueprint/screen' call -->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!-- [if lt IE8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<!-- call the title method defined in application_helper which inserts 
	the title -->
    <title><%= title %></title>
	<!-- RAILS SECURITY FEATURE cross-site request forgery (CSRF) -->
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<!-- Have to include JavaScript libraries, because web browsers can't
	  		send the Delete request issued in _user.html.erb natively-->
	<%= javascript_include_tag :defaults %>
  </head>
  <body>
	<div class="container">
		<!-- render the header partial -->
		<%= render 'layouts/header' %>
		
		<!-- body -->
		<section class="round">
			<!-- flash error messages when they are passed to the flash function -->
			<% flash.each do |key,value| %>
			  <%= content_tag(:div, value, :class => "flash #{key}") %>
			<% end %>
			<%= yield %> 

		</section>
		
		<!-- render the footer partial -->
		<%= render 'layouts/footer' %>
		<!-- adds the debugger to the site, only viewable in 'production' environment, see CH6 -->
		<%= debug(params) if Rails.env.development? %>
	</div>							
	<!-- will yield to the content of the given page -->
    
  </body>
</html>